# Generated by Django 6.0.1 on 2026-01-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='url',
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
