# Generated by Django 6.0.1 on 2026-01-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_remove_resource_url_resource_file_resource_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.CreateModel(
            name='SubjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Explanation', 'Explanation'), ('Lectures', 'Lectures'), ('Sheets', 'Sheets'), ('Midterm', 'Midterm'), ('Final', 'Final'), ('Revision', 'Revision')], max_length=50)),
                ('pdf_file', models.FileField(upload_to='resources/pdfs/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_resources', to='hub.subject')),
            ],
        ),
    ]
