# Generated by Django 6.0.1 on 2026-01-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_remove_resource_file_remove_resource_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectresource',
            old_name='pdf_file',
            new_name='file',
        ),
    ]
