# Generated by Django 6.0.1 on 2026-01-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_studentprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
