# Generated by Django 6.0.1 on 2026-01-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_delete_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
