# Generated by Django 5.2.4 on 2026-01-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_alter_level_id_alter_studentnote_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1)),
            ],
            options={
                'verbose_name': 'Portal Configuration',
                'verbose_name_plural': 'Portal Configuration',
            },
        ),
    ]
