# Generated by Django 5.2.4 on 2026-01-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_portalconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortalConfig',
            new_name='SemesterConfiguration',
        ),
        migrations.AlterModelOptions(
            name='semesterconfiguration',
            options={},
        ),
    ]
