# Generated by Django 5.2.4 on 2026-01-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_uploads/'),
        ),
    ]
