# Generated by Django 5.2.4 on 2026-01-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_alter_subjectresource_file_aichatsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rules', 'Academic Rules'), ('faq', 'FAQ')], max_length=50)),
                ('question', models.TextField(blank=True, help_text='Question for FAQs', null=True)),
                ('answer', models.TextField(help_text='The detailed answer or rule content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'University Knowledge',
            },
        ),
    ]
