# Generated by Django 5.2.4 on 2026-02-02 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0015_universityknowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='session_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
