# Generated by Django 5.2.4 on 2026-02-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0017_alter_aichatmessage_id_alter_aichatsession_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='registered_subjects',
            field=models.ManyToManyField(blank=True, related_name='registered_students', to='hub.subject'),
        ),
    ]
