# Generated by Django 5.2.4 on 2026-02-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0018_studentprofile_registered_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='subjectresource',
            name='file',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture_url',
            field=models.URLField(default='https://ui-avatars.com/api/?background=random', help_text='Image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='subjectresource',
            name='download_url',
            field=models.URLField(blank=True, help_text='Google Drive Download URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subjectresource',
            name='preview_url',
            field=models.URLField(blank=True, help_text='Google Drive Embed URL', max_length=500, null=True),
        ),
    ]
