# Generated by Django 5.2.4 on 2026-02-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_remove_chatmessage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectresource',
            name='title',
            field=models.CharField(blank=True, help_text="Specific resource name (e.g. 'Lecture 1')", max_length=255, null=True),
        ),
    ]
