# Generated by Django 5.2.4 on 2026-02-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0020_subjectresource_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectresource',
            name='drive_folder_url',
            field=models.URLField(blank=True, help_text='Source Folder URL (if imported)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subjectresource',
            name='file_id',
            field=models.CharField(blank=True, help_text='Google Drive File ID', max_length=255, null=True),
        ),
    ]
